site_name: Anotações UnB

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - admonition           # habilita !!! note, !!! example, etc.
  - pymdownx.details     # permite admonitions “dobráveis”
  - pymdownx.superfences # permite cercas de código dentro de admonitions
  - pymdownx.highlight   # títulos em blocos de código e numeração de linhas
  - attr_list            # permite atributos { } em elementos, se quiser

nav:
  - Home: index.md
  - Estrutura de Dados 1:
      - Ponteiros: disciplinas/EDA1/ponteiros.md
      - Alocação de Memória: disciplinas/EDA1/alocacao.md
      - Recurção: disciplinas/EDA1/recurcao.md
      - Análise de Complexidade: disciplinas/EDA1/complexidade.md
      - Listas Encadeadas: 
        - Listas Simplesmente Encadeadas: disciplinas/EDA1/Listas Encadeadas/simplesEncadeada.md
        - Listas Duplamente Encadeadas: disciplinas/EDA1/Listas Encadeadas/duplaEncadeada.md
      - Algoritmos de Busca: 
        - Busca Sequencial: disciplinas/EDA1/Algoritmos de Busca/buscaLinear.md
        - Busca Binária: disciplinas/EDA1/Algoritmos de Busca/buscaBinaria.md
      - Algoritmos de ordenação: 
        - Introdução: disciplinas/EDA1/Algoritmos de ordenacao/introducao.md
        - Selection Sort: disciplinas/EDA1/Algoritmos de ordenacao/selection.md
        - Bubble Sort: disciplinas/EDA1/Algoritmos de ordenacao/bubble.md
        - Insertion Sort: disciplinas/EDA1/Algoritmos de ordenacao/insertion.md
        - Shell Sort: disciplinas/EDA1/Algoritmos de ordenacao/shell.md
        - Merge Sort: disciplinas/EDA1/Algoritmos de ordenacao/merge.md
        - Quick Sort: disciplinas/EDA1/Algoritmos de ordenacao/quick.md
        - Heap Sort: disciplinas/EDA1/Algoritmos de ordenacao/heap.md
        - Intro Sort: disciplinas/EDA1/Algoritmos de ordenacao/intro.md
        - Counting Sort: disciplinas/EDA1/Algoritmos de ordenacao/counting.md
        - Radix Sort: disciplinas/EDA1/Algoritmos de ordenacao/radix.md
      - Tipos Abstratos de dados (TAD):
        - Filas: disciplinas/EDA1/Tipos Abstratos de Dados/filas.md
        - Pilhas: disciplinas/EDA1/Tipos Abstratos de Dados/pilhas.md
        - Árvores Binárias: disciplinas/EDA1/Tipos Abstratos de Dados/arvores.md
        - Árvores Binárias de Busca : disciplinas/EDA1/Tipos Abstratos de Dados/arvoreDebusca.md
  - Estrutura de Dados 2: 
      - Tabela de Símbolos: disciplinas/EDA2/tabelaSimb.md
      - Árvore Binária de Busca: disciplinas/EDA2/arvoreBin.md
      - Árvore 2-3: disciplinas/EDA2/arvore23.md
      - Árvore Red Black: disciplinas/EDA2/redblack.md
      - Skip List: disciplinas/EDA2/skipList.md
      - Tabela Hash List: disciplinas/EDA2/hash.md
      - Grafos:
         - Introdução: disciplinas/EDA2/Grafos/grafos.md
         - Grafos Dirigidos: disciplinas/EDA2/Grafos/grafosDir.md
         - Algorítmos de Caminho Mínimos: disciplinas/EDA2/Grafos/caminhoMin.md
         - Algorítmos de Árvores Geradoras Mínimas: disciplinas/EDA2/Grafos/arvoreGer.md
  - Fundamentos de Arquitetura de Computadores:
      - Assembly MIPS: disciplinas/FAC/introFAC.md
      - Arquitetura Processador MIPS: disciplinas/FAC/processador.md
  - Fundamentos de Sistemas Operacionais:
      - Introdução: disciplinas/FSO/introFSO.md
      - Processos: disciplinas/FSO/processos.md
      - Escalonamento: disciplinas/FSO/escalonamento.md
      - Threads: disciplinas/FSO/threads.md
      - Condições de Corrida: disciplinas/FSO/corrida.md
      - Fundamentos UNIX: disciplinas/FSO/unix.md
      - Gerência de Memória: disciplinas/FSO/gerenciaMem.md
      - Memória Virtual: disciplinas/FSO/memoriaVirtual.md
      - Sistema de Arquivos: disciplinas/FSO/sistemaArquivos.md
      - Gerência de Dispositivos de Entrada e Saída: disciplinas/FSO/gerencia.md
  - Requisitos de Software:
      - Introdução: disciplinas/REQ/introREQ.md
      - Elicitação: disciplinas/REQ/elicitacao.md
      - Análise e Modelagem: disciplinas/REQ/modelagem.md
      - Priorização: disciplinas/REQ/priorizacao.md
      - Especificação: disciplinas/REQ/especificacao.md
      - Gerência: disciplinas/REQ/gerencia.md
  - Banco de Dados 1:
      - Modelo Entidade Relacionamento (MER): disciplinas/BD1/mer.md
  - Arquitetura e Desenho de Software: 
      - Base:
        - Desenho de Software: disciplinas/ARQ/Base/desenho.md
        - BPMN: disciplinas/ARQ/Base/BPMN.md
  - Fundamentos de Redes de Computadores:
      - Introdução: disciplinas/REDES/introRED.md
      - CISCO Packet Tracer: disciplinas/REDES/cisco.md
  - Qualidade de Software 1:
      - Introdução: disciplinas/QUAL/introQual.md
  





